services:
  - type: web
    name: brick-backend
    runtime: python
    repo: https://github.com/Fhermei/brick-backend
    branch: main
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 10000 --reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: APP_NAME
        value: Brick SPMES API
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: postgresql://postgres.fsqcwiylxboofkgtvfez:Fatunbi1111.@aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: REDIS_URL
        value: redis://dummy:6379  # Add this - it's required by your config
      - key: AWS_REGION
        value: us-east-1
      - key: COGNITO_CLIENT_ID
        value: 6ioalvaggduenre0roa6uv9ef9
      - key: COGNITO_CLIENT_SECRET
        value: 1viv7no673ffi866mv722mmr0nhnfsrvqsett6rlj13ago8miqed
      - key: COGNITO_USER_POOL_ID
        value: us-east-1_ZZpd60SXD
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: fhermei2@gmail.com
      - key: SMTP_PASSWORD
        value: gtywediovyvpauvs
      - key: SMTP_FROM_EMAIL
        value: noreply@brickapp.com
      - key: SMTP_USE_TLS
        value: "true"
      - key: FRONTEND_URL
        value: https://brick-frontend-beige.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://brick-frontend-beige.vercel.app,http://localhost:5173